name: "update nix flake"
description: "updates a flake.lock file for updating used packages."
author: "MayNiklas"
branding:
  color: "blue"
  icon: "sun"
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/update-flake.sh
      shell: bash
